version: "3"

services:
  app:
    build:
      context: .
      args:
        UID: $LOCALUID
        UNAME: $LOCALUNAME
        GID: $LOCALGID
        GNAME: $LOCALGNAME
    ports:
      - "3100:3000"
    volumes:
      - ".:/app"
    tty: true
    stdin_open: true
    env_file: .env